<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>INHOTEL APP</title>
<link href="<?=base_url()?>assets/css/menchd.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div class="outerwrap" style="margin-top:6px;" >
<h1><span><b>PRIVACY POLICY</b></span><h1/>
<br/>
<h2><b>1. WHAT THIS PRIVACY POLICY COVERS</b></h2>
1.1 This Privacy Policy explains how InHotel (&quot;we&quot;, &quot;us&quot;, &quot;our&quot; or &quot;the Company&quot; or &quot;InHotel&quot;) collects, uses and shares your &quot;Personal Information&quot; - information that identifies, relates to, describes or is capable of being associated with you as a particular individual, such as your name, address, email address or telephone number - and other data through your use of any of InHotel&acute;s Web site, services, application programming interfaces (&quot;APP&quot;) or software (collectively, the &quot;InHotel Service&quot;).<br/>
1.2 This Privacy Policy does not apply to the practices of companies that InHotel does not own, manage or control or to Independent Contractors who InHotel does not directly employ or directly manage.<br/>
1.3 Your use of the InHotel Service is subject to this Privacy Policy in effect at the time of your use. InHotel reserves the right to update and change this Privacy Policy from time to time without notice or acceptance by you, so please check this page frequently for updates and changes. However, changes made to this Privacy Policy will not apply to you to the extent that (i) the changes concern matters which are the subject of an actual dispute between you and InHotel as of the date the changes take effect and (ii) InHotel has actual notice of the dispute as of the date the changes take effect.<br/>
1.4 This Privacy Policy shall cover and extend to all information inputted and shared by the hotels, including its representatives and/or employees, to guests who have downloaded the App and wish to share any information through InHotel app<br/>
<h2><b>2. COLLECTION OF PERSONAL INFORMATION</b></h2>
2.1 When you register for the InHotel Service, we ask for information including but not limited to your full name, company name or affiliation and email address, reason for visit, room number and Interests <br/>
This application operates an email newsletter program, used to inform subscribers about products and services supplied by this application. Users can subscribe through an online automated process should they wish to do so but do so at their own discretion. Some subscriptions may be manually processed through prior written agreement with the user. Subscriptions are taken in compliance with UK Spam Laws detailed in the Privacy and Electronic Communications Regulations 2003. All personal details relating to subscriptions are held securely and in accordance with the Data Protection Act 1998. No personal details are passed on to third parties nor shared with companies / people outside of the company that operates this website. Under the Data Protection Act 1998 you may request a copy of personal information held about you by this application's email newsletter program. A small fee will be payable. If you would like a copy of the information held on you please write to the business address at the bottom of this policy.Email marketing campaigns published by this application or its owners may contain tracking facilities within the actual email. Subscriber activity is tracked and stored in a database for future analysis and evaluation. Such tracked activity may include; the opening of emails, forwarding of emails, the clicking of links within the email content, times, dates and frequency of activity [this is by no far a comprehensive list].This information is used to refine future email campaigns and supply the user with more relevant content based around their activity.In compliance with UK Spam Laws and the Privacy and Electronic Communications Regulations 2003 subscribers are given the opportunity to un-subscribe at any time through an automated system. This process is detailed at the footer of each email campaign. If an automated un-subscription system is unavailable clear instructions on how to un-subscribe will by detailed instead.<br/>
2.2 InHotel collects the email addresses of people who communicate with InHotel via email, create accounts, download the Services, and/or post topics.<br/>
2.3 InHotel may also collect Personal Information volunteered by users (such as through posts, survey information and/or site registrations). When you post content on or through the InHotel Service, please keep in mind that any Personal Information you post may be viewed by others.<br/>
2.4 InHotel may collect billing and account information for credit cards, payment cards or other payment systems from clients of paid versions of the InHotel Service and share this information with InHotel&acute;s billing and payment processor(s). InHotel does not store credit card or payment card numbers after they have been forwarded to its billing and payment processor(s).<br/>
2.5 InHotel may collect information about your transactions with us and/or with our business partners and/or resellers at our discretion. This information might include information necessary to process payments, such as billing information and your credit card number.<br/>
2.6 InHotel may receive information about you from our business partners with which you have an account, service relationship or transaction history.<br/>
2.7 InHotel may obtain information about you from service providers engaged in the business of marketing data.<br/>
2.8 InHotel may receive Personal Information from third parties when you authorize such third parties to authenticate or identify you to InHotel or sign in to the InHotel Service using credentials from a third party service.
<h2><b>3. USE OF PERSONAL INFORMATION</b></h2>
3.1 InHotel uses Personal Information it collects for the following general purposes: products and services provision, billing, identification and authentication, services improvement, contact, research, analytics and reporting.<br/>
3.2 To receive optional email messages such as newsletters, you will be required to provide us with your email address. In addition to these optional email messages, InHotel may contact you via any email address you provide to us with transactional or relationship messages such as account status messages, security updates or notifications of changes in the terms of your account or the InHotel Service. These types of transactional or relationship email messages are not optional.<br/>
3.3 Users contacting this application and/or its owners do so at their own discretion and provide any such personal details requested at their own risk. Your personal information is kept private and stored securely until a time it is no longer required or has no use, as detailed in the Data Protection Act 1998. Every effort has been made to ensure a safe and secure form to email submission process but advise users using such form to email processes that they do so at their own risk. 
Users contacting this application and/or its owners do so at their own discretion and provide any such personal details requested at their own risk. 
Your personal information is kept private and stored securely until a time it is no longer required or has no use, as detailed in the Data Protection Act 1998. 
Every effort has been made to ensure a safe and secure form to email submission process but advise users using such form to email processes that they do so at their own risk.<br/>
3.4 This application and its owners use any information submitted to provide you with further information about the products / services they offer or to assist you in answering any questions or queries you may have submitted. This includes using your details to subscribe you to any email newsletter program the website operates but only if this was made clear to you and your express permission was granted when submitting any form to email process. Or whereby you the consumer have previously purchased from or enquired about purchasing from the company a product or service that the email newsletter relates to. This is by no means an entire list of your user rights in regard to receiving email marketing material. Your details are not passed on to any third parties.<br/>

3.5 InHotel may automatically receive and record information on our server logs from your browser, including your IP address, cookies and the pages you request. This information may be used for various purposes, including to:<br/>
3.5.1 Diagnose and prevent service or technology problems reported by our users or engineers that are associated with the IP addresses controlled by a specific web company or ISP.
3.5.2 Estimate the total number of users visiting the InHotel Service from specific geographical regions.<br/>
3.5.3 Help determine which users have access privileges to certain content, services or resources that we offer.<br/>
3.5.4 Estimate and report our total audience size and traffic.<br/>
3.5.5 Conduct research to improve the InHotel Service.<br/>
3.5.6 Help combat fraud and abuse.<br/>
3.5.7 Provide analytics and reporting.<br/>
3.6 InHotel may combine information about you in our possession with information we obtain from business partners or others.<br/>
<h2><b>4. SHARING OF PERSONAL INFORMATION</b></h2>
4.1 InHotel does not share Personal Information collected from your use of the InHotel Service with others, except as described in this Privacy Policy.<br/>
4.2 InHotel may share your Personal Information when you have authorized InHotel to do so, when it is necessary to complete a transaction, to operate or improve the InHotel Service or to take some action that you have asked us to do.<br/>
4.3 InHotel may share your email address and profile information with companies that are clients, partners, resellers of the InHotel Service. How such companies use your email address is subject to those companies&acute; own privacy policies, not this Privacy Policy.<br/>
4.4 InHotel may share Personal Information under the following circumstances:<br/>
4.4.1 In the course of operating our business, it may be necessary or appropriate for us to provide access to your Personal Information to others such as our service providers, contractors and select vendors so that we can operate the InHotel Service and our business. Where practical, we seek to obtain confidentiality agreements that are consistent with this Privacy Policy and limit others&acute; use or disclosure of this Personal Information.<br/>
4.4.2 We may share your Personal Information to respond to subpoenas, court orders, or legal process, to establish or exercise our legal rights, to defend against legal claims or in such circumstances where, in our judgment, disclosure is required or appropriate.<br/>
4.4.3 We may share your Personal Information if we believe it is necessary in order to investigate, prevent or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of our various terms of service or as otherwise required by law.<br/>
4.4.4 As we continue to develop our business, we may sell all or part of our business. In such transactions, Personal Information collected from users is generally one of the business assets that will be transferred. The transferred Personal Information will remain subject to this Privacy Policy or subsequent policies to which you have consented.<br/>
.
<h2><b>5. INFORMATION RELATING TO CHILDREN</b></h2>
6.1 We do not knowingly collect or solicit Personal Information from children under the age of majority or knowingly allow children under the age of majority to register for the InHotel Service. If you are under the age of majority, do not register or attempt to register for any of the InHotel Service or send any information about yourself to us. No one under the age of majority may provide any Personal Information to, on or through the InHotel Service.<br/>
6.2 If we learn that we have collected or been sent Personal Information from a child under the age of majority, we will delete that Personal Information as soon as reasonably practical. If you believe that we might have collected or been sent Personal Information from a child under the age of majority, please contact our Support team.
<h2><b>6. DATA WE COLLECT OTHER THAN PERSONAL INFORMATION</b></h2>
7.1 In addition to Personal Information, we collect data on your use and interaction with the InHotel Service. Data which we obtain about you, other than Personal Information, is the exclusive property of  InHotel and may be used by InHotel in any manner permitted by applicable laws.
<h2><b>7. RETENTION OF PERSONAL INFORMATION AND OTHER DATA</b></h2>
7.1 InHotel reserves the right to retain your Personal Information, other data collected about you and content you submit to or through the InHotel Service to the extent required by applicable laws, rules and regulations and as reasonably necessary to protect our legal interests and operate our business.
<h2><b>8. DATA TRANSMISSION AND STORAGE</b></h2>
9.1 No data transmission over the Internet can be guaranteed to be 100% secure. Consequently, we cannot ensure or warrant the security of any information you transmit to us and you do so at your own risk.<br/>
9.2 InHotel may use third party vendors and/or hosting partners to provide the necessary hardware, software, networking, storage, and related technology required to run the InHotel Service. Where practical, we seek to obtain confidentiality agreements that are consistent with this Privacy Policy and that limit others&acute; use or disclosure of your Personal Information.<br/>
<h2><b>9. INTERNATIONAL USE</b></h2>
19.1 The InHotel Service is hosted in by Namecheap in the United States. If you use the InHotel Service from outside of the United States, you acknowledge that you are voluntarily transferring information (potentially including Personal Information) to the United States and agree that InHotels&acute;s collection, use, storage and sharing of your information is exclusively subject to the laws of the United States, not of the jurisdiction in which you are located. Under some circumstances, the laws of UK may apply as InHotel is incorporated in UK.<br/>
<h2><b>11. QUESTIONS</b></h2>
11. Any questions about this Privacy Policy should be addressed to <b>info@inhotel-app.com</b>

</div> 
</body>
</html>
