<?php $this->load->view('header'); ?>

<div  class="grn_bg_in">
  <div class="container">
    <h2>TERMS & CONDITIONS </h2>
  </div>
</div>
<div class="container gbg_in">
  <div class="row">
<h1><b>ACCEPTANCE OF TERMS OF SERVICE</b></h1>
<br/>
1.1Welcome to InHotel (hereinafter &quot;we&quot; &quot;us&quot; &quot;our&quot; &quot;the Company&quot; or &quot;InHotel app&quot;).<br/>
1.2 Your use of any of InHotel&acute;s websites, services, application programming interfaces (hereinafter &quot;APP&quot;) or software (collectively, the &quot;InHotel app Service&quot;) is subject to these terms of service (the &quot;Terms of Service&quot;) in effect at the time of your use. InHotel&acute;s Terms of Service commences from the time you sign up for our free trial account and governs for the entire duration of your use of our services. InHotel reserves the right to update and change these Terms of Service from time to time without notice or acceptance by you, so please check this page frequently for updates and changes. However, changes made to these Terms of Service will not apply to you to the extent that (i) the changes concern matters which are the subject of an actual dispute between you and InHotel as of the date the changes take effect and (ii) InHotel has actual notice of the dispute as of the date the changes take effect.<br/>
1.3 Your use of the InHotel Service is also subject to the InHotel Privacy Policy in effect at the time of your use, which is incorporated herein as though set forth in full. InHotel&acute;s Privacy Policy commences from the time you sign up for our free trial account and governs for the entire duration of your use of our services. <br/>
1.4 Your use of the InHotel APP is also subject to the InHotel APP Terms of Service in effect at the time of your use, which are incorporated herein as though set forth in full.<br/>
1.5 Your use of the InHotel Service may also be subject to additional terms, conditions, policies and/or agreements applicable to a specific website, service, API, software, service level or version. In the event of any conflict between these Terms of Service and such additional terms, conditions, policies and/or agreements, the additional terms, conditions, policies and/or agreements will control. For the avoidance of doubt, if there are terms and conditions in these Terms of Service regarding subjects on which the additional terms, conditions, policies and/or agreements are silent, such silence will not constitute a conflict and the terms and conditions in these Terms of Service will control.<br/>
1.6 By signifying your acceptance of these Terms of Service including but not limited to making any use of the InHotel Service, you signify your irrevocable acceptance of these Terms of Service in effect at the time of your use. If you are an individual acting as a representative, whether or not you were explicitly or implicitly given permission, of a corporation or other legal entity to sign up for and/or use the InHotel Service, then you represent and agree that you have the full legal authority to accept these Terms of Service on behalf of such corporation or legal entity and that all provisions of these Terms of Service will bind that corporation or other legal entity as if it were named in these Terms of Service in place of you.<br/>
1.7 By signing up and/or creating an account with InHotel, you agree to receive occasional emails from us regarding your account and/or InHotel in general, including but not limited to new feature launches, marketing tips, questionnaires, etc.<br/>



<h2><b>2. YOUR ACCOUNT</b></h2>
2.1 The  InHotel Service is not intended for users under the age of majority. By signifying your acceptance of these Terms of Service or making any use of the InHotel Service, you represent and warrant that you are of the age of majority in effect in the jurisdiction for download and/or use.<br/>
2.2 InHotel can refuse registration of, suspend, delete, or cancel, any account at its sole discretion and at any time, with or without notice to the user.<br/>
2.3 Your account will be accessed through a user ID and password that you will create (your &quot;Credentials&quot;). Your Credentials are solely for your use. You are responsible for maintaining the confidentiality of your Credentials and you are fully and solely responsible for all activities that occur under your Credentials, whether authorized by you or not. It is your responsibility to take adequate precautions with your Credentials and to immediately notify InHotel of any unauthorized use of your Credentials. InHotel will not bear any fault, liability or responsibility regarding Credentials.<br/>
2.4 Using your account, you may access and participate in the InHotel Service, including viewing, posting and responding to communications on and through the InHotel Service.<br/>
2.5 InHotel will freeze, disable, inactivate, turn off, delete and/or suspend your account on InHotel which was created but not upgraded to a paying account though credit card payment within fourteen (14) days counting from the sign up date, with or without notice.<br/>
2.6 Current clients signed up on InHotels&acute;s free packages will receive fourteen (14) days to upgrade their account to any of paying packages until InHotel will freeze, disable, inactivate, turn off, delete and/or suspend your account. Current sign ups on InHotel&acute;s free package may or may not be notified.<br/>
<h2><b>3. CONTENT AND INTELLECTUAL PROPERTY</b></h2>
3.1 Your own text, images, audiovisual media and any other form of intellectual property, including the data, ideas, inventions, designs, patterns and processes in such material (collectively, &quot;Content&quot;) that you post on or through the InHotel Service belongs to you and you may use it in any way without restriction. But by using the InHotel Service, you are granting InHotel and certain third parties permission to view and/or use your Content as described in these Terms of Service.<br/>
3.2 By using the InHotel Service, you are granting  InHotel a non-exclusive, worldwide, royalty-free, sub-licensable and transferable right and license to use, reproduce, create derivative works of, distribute, publicly perform and publicly display your Content on and through the InHotel Service and on and through services affiliated with InHotel, regardless of the form of media used or of whether such services now exist or are developed in the future.This grant of right is given to  InHotel by you in perpetuity and is irrevocable after given by you. If you post Content on or through the  InHotel Service, you represent and warrant that you have full legal rights to ownership, use, distribute, upload, share, post said Content and to grant the above rights to InHotel.<br/>
3.3 InHotel may preserve your Content and may also disclose such Content, with or without notice to you, if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce these Terms of Service; (c) respond to claims that your Content violates the rights of any third party; or (d) protect the rights, property, or personal safety of InHotel, its users and the public.<br/>
3.4 You understand that posting your Content on or through the InHotel Service is entirely voluntary and will expose your Content to public display in a non-confidential manner. You understand that  InHotel and/or any past, present or future client of InHotel (each, a &quot;Client&quot;) may view your Content and may develop or have developed Content which is identical or similar to yours, may already know of such Content from other sources or may have taken or will take some other action with respect to such Content. Therefore, you represent and agree to all of the following and acknowledge that  InHotel and its Clients are explicitly relying on such representations and agreement with regard to your Content:
<br/>3.4.1 The Content represents your own original work and you have all necessary rights to disclose the Content. In doing so, you are not violating the rights of any third party and you know of no other individual or entity whose rights will be infringed by the Content being viewed and used as described in these Terms of Service.
<br/>3.4.2 Your disclosure of the Content does not violate a confidential relationship with any third party, establish a confidential relationship with InHotel or any of its Clients or obligate  InHotel or any of its Clients to treat your Content (or any related materials) as secret or confidential.
<br/>3.4.3 InHotel and/or any of its Clients may give your Content such consideration as is warranted by their respective judgments. Review of your Content shall not be construed as any recognition of the novelty or originality of the Content. Neither InHotel, nor any of its Clients, is obligated to give reasons for making use of or rejecting your Content or to reveal its activities that are related to your Content.
<br/>3.4.4 Neither InHotel nor any of its Clients has any obligation, either express or implied, to make any use of your Content. However, if InHotel and/or any of its Clients do make use of your Content, whether such use is intentional or inadvertent, no compensation will be due to you or anyone else for the use of your Content or the use of any data, ideas, inventions, designs, patterns and/or processes similar to, related to or derived from your Content.
<br/>3.4.5 Neither InHotel nor any of its Clients assumes any obligation with respect to any of your Content except as set forth in these Terms of Service, unless and until it enters into a separate written contract with you, and then only as expressed in that separate written contract. In the absence of a separate written contract, your rights with regard to InHotel or any of its Clients&acute; user of your Content shall be as described in these Terms of Service and as existing under the patent laws of the appropriate jurisdiction.
<br/>3.4.6 If your Content is the subject of a pending or issued patent, copyright, or trademark matter you have disclosed or will disclose that fact in connection with posting your Content on or through the InHotel Service. To the extent you hold a patent, copyright, or trademark right and/or ownership in the Content, no license under any patent, copyright, or trademark is herein granted. Any license to use patented, copyright, or trademark Content shall be in the form of a separate written contract, in which event your, InHotel&acute;s and/or any of its Clients&acute; respective obligations shall be only those expressed in such separate written contract.
<br/>3.4.7 You hereby irrevocably release and forever discharge InHotel and its Clients and their affiliates and subsidiaries (together, the &quot;Released Parties&quot;) from any and all actions, causes of actions, claims, damages, liabilities and demands, whether absolute or contingent and of any nature whatsoever, which you now have or hereafter can, shall or may have against the Released Parties or their respecting successors and assigns with respect to the Content, including without limitation in respect of how the Released Parties, directly or indirectly, use the Content, with the sole exception that the foregoing release and discharge does not apply to your right to bring a claim of patent infringement arising from use of your Content.<br/>
3.5 Content posted by another person or company on or through the InHotel Service belongs to the poster. Except as expressly permitted in these Terms of Service, you do not have the right to use, reproduce, create derivative works of, distribute, publicly perform or publicly display any Content that does not belong to you, other than viewing of the Content on or through the InHotel Service as InHotel may make available.<br/>
3.6 InHotel owns the InHotel Service as a whole, including all computer code, graphics, user interfaces, domain name, server account, InHotel website, developer accounts, audiovisual content, marketing materials, used to provide the InHotel Service, and the combination of all the elements on the InHotel Service. The  InHotel Service as a whole, including but not limited to the computer code of the InHotel Service, the user interface and graphic elements are all copyrighted works of  InHotel. Various other aspects of the  InHotel Service may be protected by intellectual property laws including laws of copyright, trademark, service mark, patent and trade secret of various countries.<br/>
<h2><b>4. CODE OF CONDUCT</b></h2><br/>
4.1 InHotel shall immediately terminate without notification to the user Apps that violate these Terms of Service, to be unlawful, offensive, threatening, libelous, defamatory, obscene or otherwise objectionable, that violates any party&acute;s intellectual property or that is detrimental to the quality or intended spirit of the InHotel Service.<br/>
4.2 InHotel will use common sense and business sense regarding Content or behavior allowed on or through the InHotel Service. Examples of unacceptable Content or behavior, which are grounds for immediate termination without notice from  InHotel, include:<br/>
4.2.1 Abuse, harassment, threats, flaming or intimidation of any person or organization.<br/>
4.2.2 Engaging in or contributing to any illegal activity or activity that violates others&acute; rights.<br/>
4.2.3 Use of derogatory, discriminatory or excessively graphic language.<br/>
4.2.4 Providing information that is false, misleading or inaccurate.<br/>
4.2.5 Hacking or modifying the InHotel Service or another Web site to falsely imply an association with InHotel.<br/>
4.2.6 Implying or pretending to be affiliated with a company or organization with which you are not affiliated, or misrepresenting the extent of your affiliation or role with an affiliated company or organization.<br/>
4.2.7 Transmitting worms, viruses or harmful software.<br/>
4.2.8 Sending unwanted messages to other users (aka &quot;spam&quot;).<br/>
4.2.9 Disclosing personal or proprietary information of another person or organization.<br/>
4.2.10 Providing, showing, commenting, alluding to pornographic material, defined by Webster&acute;s Dictionary as &quot;explicit descriptions or displays of sexual organs or activities intended to stimulate erotic rather than aesthetic or emotional feelings&quot;<br/>
4.2.11 Containing user generated content that is frequently pornographic (ex &quot;Chat Roulette&quot; apps)
4.2.12 Containing references or commentary about a religious, cultural or ethnic group that are defamatory, offensive, mean-spirited or likely to expose the targeted group to harm or violence. App may contain or quote religious text provided the quotes or translations are accurate and not misleading. Commentary should be educational or informative rather than inflammatory.<br/>
4.2.13 solicit, promote, or encourage criminal or clearly reckless behavior<br/>
4.3 InHotel cannot and need not control all Content posted by third parties on or through the  InHotel Service, and does not guarantee the accuracy, integrity or quality of such Content. You understand that by using the InHotel Service you may be exposed to Content that you may find offensive, indecent, incorrect or objectionable and you agree that under no circumstances will  InHotel be liable in any way for any Content, including any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of your use of any Content. You understand that you must evaluate and bear all risks associated with the use of any Content, including any reliance on the content, integrity, and accuracy of such Content. Urgent issues can be reported to Info@inhotel-app.com<br/>
4.4 All Apps must comply with all legal requirements in any location where they are made available to end-users. It is the users&acute; obligation to understand and conform to all local laws and users agree to hold InHotel harmless, either directly or indirectly, for any and all claims which may be brought against InHotel for violation of any local laws where the end user downloads, uses, shows the App. If said damages involves damages, either compensatory punitive or special, the user agrees to bear all financial and/or legal responsibility whether in law or restitution.<br/>
<h2><b>5. INTERNATIONAL USE</b></h2>
5.1 The InHotel Service is hosted in by NameCheap in the United States. If you use the InHotel Service from outside of the United States, you acknowledge that you are voluntarily transferring information (potentially including Personal Information) to the United States and agree that InHotels&acute;s collection, use, storage and sharing of your information is exclusively subject to the laws of the United States, not of the jurisdiction in which you are located. Under some circumstances, the laws of UK may apply as InHotel is incorporated in UK.
5.2 You will comply with all UK rules and regulations applicable to the export of products, services, software and technical data regardless of the jurisdiction in which you are located as InHotel is incorporated in UK. Additionally or separately, You will comply with the UK Intellectual Property Laws.
<h2><b>6. COPYRIGHT INFRINGEMENT</b></h2><br/>
6.1 Copyright Infringement Notices. If you believe that any material available on or through the InHotel Service violates your copyright, you may send InHotel a copyright infringement notice and include substantially all of the following:<br/>
6.1.1 A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.<br/>
6.1.2 Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site.<br/>
6.1.3 Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit InHotel to locate the material. InHotel requests that complete URLs for each instance of the allegedly infringing material be provided.<br/>
6.1.4 Information reasonably sufficient to permit InHotel to contact you, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted.<br/>
6.1.5 A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.<br/>
6.1.6 A statement that the information in the copyright infringement notice is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed<br/>
6.1.7 Your written copyright infringement notice must be sent to InHotel&acute;s designated copyright agent via mail or email. Please be aware that any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.<br/>
6.2 Copyright Abuse Policy.<br/>
InHotel will terminate, in appropriate circumstances, account holders of InHotel&acute;s system or network who are repeat copyright infringers in addition or reserving the right to pursue any and all legal claims for injunctions or damages.
<h2><b>7. CANCELLATION AND TERMINATION</b></h2><br/>
7.1 InHotel, in its sole discretion and without notice to you, may terminate, suspend or delete your password and/or account and remove and discard any Content within the InHotel Service for any reason, including and without limitation including but not limited to lack of use, or if InHotel believes that you have violated or acted inconsistently with the letter or spirit of these Terms of Service. In such event, any contracts, verbal or written or assumed, in conjunction with your account and all its parts, at InHotel&acute;s discretion, will be terminated as well.<br/>
7.2 InHotel, in its sole discretion and at any time, may discontinue providing the InHotel Service, or any part thereof, with or without notice. Any termination of your access to the InHotel Service under any provision of these Terms of Service may be effected without prior notice. InHotel may immediately deactivate or delete your account, as applicable, and all related information and Content and bar any further access to such information, Content or to the InHotel Service. InHotel will not be liable to you or any third party for any termination of your access to the InHotel Service.<br/>
7.3 After cancellation or termination of your account for any reason, you will no longer have access to your account and all information and Content in your account or that you have stored on InHotel Service may be, but is not required to be, deleted by InHotel. InHotel will have no liability for information or Content that is deleted due to the cancellation or termination of your account for any reason.<br/>
<h2><b>8. ADDITIONAL TERMS APPLICABLE TO CLIENTS of INHOTEL</b></h2>
8.1 If you are a Client of the InHotel Service, the following terms shall apply to you.<br/>
8.2 Subscriptions to the InHotel Service may be made available in free or paid versions and/or in different service levels. Not all of the features and functionality of the InHotel Service may be available in each version or service level. The features and functionality of each version or service level may be changed from time to time at InHotel&acute;s discretion, with or without notice to you. InHotel may, but is not obligated to, notify each user upon any change.<br/>
8.3 In order to subscribe to the InHotel Service, you may be required to provide InHotel with billing and account information (&quot;Billing Information&quot;) for a credit card, payment card or another payment system for which you are authorized to approve charges (each, a &quot;Payment Source&quot;) to allow InHotel to collect payment from you for your use of the InHotel Service. You must provide InHotel with true, accurate, current and complete Billing Information and maintain and promptly update your Billing Information to keep it true, accurate, current and complete.<br/>
8.4 Unless other payment arrangements have been made in advance and confirmed by InHotel, you authorize InHotel to automatically and immediately bill your Payment Source when charges for your use of the paid version of the InHotel Service are due, without any further action on your part or other prior notice on the part of InHotel. You assume full responsibility for such charges, even if such charges are declined or not paid by your Payment Source.<br/>
8.5 If your Payment Source is invalid, if charges billed to your Payment Source are declined or not paid or if you fail to pay charges for a paid version of the InHotel Service when due, your account may be downgraded, suspended or cancelled, at InHotel&acute;s discretion. If your account is suspended, InHotel may, but is not obligated to, maintain your account and/or related content and information, in order to allow you pay the past-due charges and restore your account. If the charges are not paid, your account may be cancelled.
8.6 Unless stated to the contrary, all charges for paid versions of the InHotel Service are non-refundable, even if your use of the paid version of the InHotel Service is cancelled before the end of your current billing period.<br/>
8.7 Unless stated to the contrary, all currency references in paid versions of the InHotel Service are in U.S. Dollars or English Pounds.<br/>
8.8 In addition to any other remedies available to InHotel, you may be required to pay a late fee of one percent (1%) per month (or the maximum amount permitted by applicable law, whichever is less) for any late payments hereunder.<br/>
8.9 You are solely responsible for any and all taxes, levies, charges, bank charges, transfer fees, currency differences if applicable, and other payment transfer related fees incurred or that may be payable to any taxing authority in connection with the transactions hereunder, other than any income tax incurred by InHotel. All fees stated for use of the InHotel Service are net of any applicable taxes.<br/>
8.10 InHotel grants to you, commencing on the effective date of your subscription to the InHotel Service (the &quot;Effective Date&quot;) and continuing thereafter for the term of your subscription (unless terminated earlier pursuant to these Terms of Service), a non-exclusive, non-transferable (except as permitted below), world-wide, limited license to make use of the then-current versions of the InHotel Service to which you have subscribed for the purposes of creating, maintaining and administering a marketing and sales tool for your hotel property. The InHotel Service is licensed hereby, not sold.<br/>
8.11 &quot;Client Content&quot; means any content owned, controlled or licensed by you. You hereby grant to InHotel a non-exclusive, transferable, worldwide, royalty-free, limited license to reproduce, create derivative works from, distribute, perform, display and otherwise use the Client Content for the sole purpose of providing the InHotel Services.<br/>
8.12 &quot;User Content&quot; means any content uploaded to InHotel Services by any user of the Services. To the extent of your rights in and to the User Content, you hereby grant to InHotel a non-exclusive, transferable, worldwide, royalty-free, perpetual license to reproduce, create derivative works from, distribute, perform, display, and otherwise use the User Content (i) for the sole purpose of providing the InHotel Service, (ii) for use in and through InHotel&acute;s APP to the extent authorized by the user of the Services who made the User Content available to InHotel, (iii) for syndicating the User Content to third parties to the extent authorized by the user of the Services who made the User Content available to  InHotel and (iv) to retain the User Content to the extent authorized by the user of the Services who made the User Content available to InHotel.<br/>
8.13 To comply with applicable laws and lawful governmental requests, to protect InHotel&acute;s systems and customers, or to ensure the integrity and operation of InHotel&acute;s business and systems, InHotel may access, store and/or disclose any information stored or transmitted on or through the Services which InHotel considers necessary or appropriate, including, without limitation, user information, IP address and traffic information, usage history, Client Content and User Content. InHotel also reserves the right to report any activity that it suspects violates any law, rule or regulation to appropriate law enforcement officials, regulators or other appropriate third parties.<br/>
8.14 You may not assign your subscription to the InHotel Service, and such any assignment by you will be null and void; provided, however, that you may assign your subscription to the InHotel Service to its successor in interest.<br/>
8.15 You are bound by the terms and conditions contained in App Store Marketing Guidelines accessible at https://developer.apple.com/appstore/AppStoreMarketingGuidelines.pdf
InHOTEL HEREBY DISCLAIMS ANY LIABILITY FOR ANY VIOLATIONS OR NON-COMPLIANCE TO THE APP STORE MARKETING GUIDELINES SHOULD YOU WISH TO USE ANY APP STORE AND/OR APPLE MARKETING MATERIALS FOR ANY OF THE HOTEL&acute;S MARKETING CHANNELS. IF THIS SITUATION WERE TO ARISE, NEITHER INHOTEL NOR ITS AFFILIATES WILL BE LIABLE, UNDER ANY THEORY OF LAW, FOR ANY INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES, INCLUDING, BUT NOT LIMITED TO LOSS OF PROFITS, BUSINESS INTERRUPTION, AND/OR LOSS OF INFORMATION OR DATA. YOU AGREE TO HOLD INHOTEL HARMLESS AND INDEMNIFY INHOTEL IN THIS CIRCUMSTANCE.<br/>
<h2><b>9. GENERAL TERMS</b></h2>
9.1 These Terms of Service will remain in full force and effect while you use the InHotel Service. Those terms that can continue to operate after you stop using the InHotel Service (including without limitation your Content license to InHotel and the General Terms in this Section), will survive after you stop using the InHotel Service.<br/>
9.2 You agree to indemnify and hold InHotel, its parents, subsidiaries, partners, channels, affiliates, shareholders, directors, officers and employees, harmless, including costs and attorneys&acute; fees, from any claim or demand made by any third party due to or arising out of (i) your actions in using the InHotel Service, (ii) a claim that you, or any third party using your Credentials, infringed any intellectual property or other right of any person or organization using the InHotel Service, or (iii) the violation of these Terms of Service by you, or any third party using your Credentials.<br/>
9.3 THE INHOTEL SERVICE IS PROVIDED &quot;AS IS&quot; WITH NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS, STATUTORY OR IMPLIED, AS TO THE OPERATION OF THE INHOTEL SERVICE, OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDED ON THE INHOTEL SERVICE. TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, INHOTEL AND ITS AFFILIATES DISCLAIM ALL WARRANTIES, EXPRESS, STATUTORY, OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. FURTHER, INHOTEL AND ITS AFFILIATES DO NOT WARRANT THE ACCURACY OR COMPLETENESS OF THE INFORMATION, TEXT, GRAPHICS, LINKS OR OTHER INFORMATION CONTAINED IN THE INHOTEL SERVICE. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. INHOTEL DOES NOT WARRANT THAT THE INHOTEL SERVICE WILL BE AVAILABLE AT ANY TIME OR FROM ANY PARTICULAR LOCATION, WILL BE SECURE OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE INHOTEL SERVICE IS FREE OF VIRUSES OR OTHER POTENTIALLY HARMFUL COMPONENTS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM INHOTEL OR THE INHOTEL SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS OF SERVICE.<br/>
9.4 NEITHER INHOTEL NOR ITS AFFILIATES WILL BE LIABLE, UNDER ANY THEORY OF LAW, FOR ANY INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES, INCLUDING, BUT NOT LIMITED TO LOSS OF PROFITS, BUSINESS INTERRUPTION, AND/OR LOSS OF INFORMATION OR DATA. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, INHOTEL&acute;S MAXIMUM AGGREGATE LIABILITY TO YOU FOR ANY CAUSES WHATSOEVER, AND REGARDLESS OF THE FORM OF ACTION, WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (i) THE AMOUNT PAID, IF ANY, BY YOU TO INHOTEL FOR THE INHOTEL SERVICE IN THE 12 MONTHS PRIOR TO THE ACTION GIVING RISE TO LIABILITY OR (ii) ONE HUNDRED U.S. DOLLARS ($100.00).<br/>
9.5 The scope of use for InHotel is FOR HOTELS ONLY; USE OF OUR SERVICE BY AND FOR NON-HOTEL BUSINESSES IS STRICTLY PROHIBITED. USE BY NON-HOTELS WILL RESULT IN THE APP AUTOMATICALLY BEING TERMINATED, DELETED AND/OR DESTROYED BY INHOTEL AND/OR ITS AFFILIATES. Additionally, use, sign-up, and/or distribution of the App by and for non-hotel businesses (including prostitution) shall be subject to liability and/or legal claims by the Company, Apple, Google, and/or any third party whose interests concern this scope limitation.<br/>
9.6 InHotel shall not be held liable for cancellation or termination of its services in the event that Apple and/or Google forbids, disallows, prevents or otherwise makes its services unavailable for the delivery of our App services through iTunes or another Apple platform and/or by Google through the Play Store. If this occurs, InHotel shall terminate effective immediately all subscription charges to clients with or without notification to users; however, InHotel will not reimburse any previous payments made prior to this event including but not limited to deposit payments. In this situation, NEITHER INHOTEL NOR ITS AFFILIATES WILL BE LIABLE, UNDER ANY THEORY OF LAW, FOR ANY INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES, INCLUDING, BUT NOT LIMITED TO LOSS OF PROFITS, BUSINESS INTERRUPTION, AND/OR LOSS OF INFORMATION OR DATA.<br/>
9.7 InHotel reserves the right to use any profile (including texts, photos, logos, etc) registered and/created by any person for any hotel, whether the user has a free or paid account, at any time for promotional and advertising purposes; this also includes the users&acute; commercial and proprietary content, text, logo, brand, signage, images, photographs, perspectives, and other materials. InHotel has sole discretion to use any profile on its server for any advertising and promotional services at any time. By signing up for and using InHotel&acute;s services, you are consenting to and providing permission to this usage.<br/>
9.8 These Terms of Service (including any additional terms, conditions, policies and agreements incorporated herein) are the entire agreement between InHotel and you regarding the InHotel Service. Any dispute arising from or related to these Terms of Service will be governed by the laws of UK without regard to conflict of law principles. Any such dispute will be resolved through binding arbitration by an arbitration board pursuant to the UK International Arbitration Centre&acute;s rules applicable to commercial disputes. The arbitration will be held in UK and conducted in the English language.<br/>
9.9 WAIVER - InHotel&acute;s failure to enforce your strict performance of any section of this Terms of Service will not constitute a waiver of InHotel&acute;s right to subsequently enforce such a provision or any other section of this Terms of Service.<br/>
9.10 If any provision of these Terms of Service is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms of Service shall otherwise remain in full force and effect and be fully enforceable.<br/>
9.11 TRADEMARK AND INTELLECTUAL PROPERTY OF APPLE PRODUCTS AND SERVICES. Apple, the Apple logo, iPad, iPhone, iPad mini and iPod touch are trademarks of Apple Inc., registered in the U.S. and other countries. App Store is a service mark of Apple Inc. iTunes is for legal or rightholder-authorized copying only. Don&acute;t steal music. Android is owned by Google.<br/>
9.12 INDEMNITY CLAUSE - You, including your affiliated parties, agree to indemnify and hold harmless InHotel, its subsidiaries, affiliates, partners, directors, officers, employees, agents, shareholders, members, and other owners, against any and all claims, actions, demands, liabilities, losses, damages, judgments, settlements, costs, and expenses, including reasonable attorneys&acute; fees (any or all of the foregoing hereinafter referred to as &quot;Losses&quot;), at law or in restitution, and for any and all areas of law including but not limited to intellectual property law, insofar as such Losses, or actions in respect thereof, arise out of or are based on any claim not attributable to InHotel.

<br/>



<h2><b>
10. QUESTIONS</b></h2>
Any questions about these terms and conditions should be addressed to <b>info@inhotel-app.com</b>.<br/>

<!--<h2><b>13. UPDATED LAST</b></h2>
Last updated August 2015-->

    </div>
  <div class="col-lg-12 "><img src="<?php echo base_url();?>images/bg.jpg" width="100%"></div>
</div>
<?php $this->load->view('footer'); ?>
